### ISSUE TITLE
launch_app (Netflix) does'nt work 

### ISSUE THREAD

**Issue by popy2k14** [eslavnov/pylips#17]
I am trying to start netflix, youtube, kodi with pylips.
Sadly without luck.
Your examples doesnt also work for me.
I have tried to get the needed informations from this endpoint https://github.com/eslavnov/pylips/wiki/Applications-(GET)
but without luck on using it.

My TV has android pie on it, maybe thats the reason?

Here is the output of my applications:

`
{"version":2,"applications":[{"label":"Wie Sie...","intent":{"component":{"packageName":"org.droidtv.eum","className":"org.droidtv.eum.onehelp.HowToTutorials.HowToVideosActivity"},"action":"android.intent.action.MAIN"},"order":0,"id":"org.droidtv.eum.onehelp.HowToTutorials.HowToVideosActivity-org.droidtv.eum","type":"app"},{"label":"Play Store","intent":{"component":{"packageName":"com.android.vending","className":"com.google.android.finsky.tvmainactivity.TvMainActivity"},"action":"android.intent.action.MAIN"},"order":0,"id":"com.google.android.finsky.tvmainactivity.TvMainActivity-com.android.vending","type":"app"},{"label":"YouTube","intent":{"component":{"packageName":"com.google.android.youtube.tv","className":"com.google.android.apps.youtube.tv.activity.ShellActivity"},"action":"android.intent.action.MAIN"},"order":0,"id":"com.google.android.apps.youtube.tv.activity.ShellActivity-com.google.android.youtube.tv","type":"app"},{"label":"Prime Video","intent":{"component":{"packageName":"com.amazon.amazonvideo.livingroom","className":"com.amazon.ignition.IgnitionActivity"},"action":"empty"},"order":0,"id":"com.amazon.ignition.IgnitionActivity-com.amazon.amazonvideo.livingroom","type":"app"},{"label":"Play Musik","intent":{"component":{"packageName":"com.google.android.music","className":"com.google.android.music.tv.HomeActivity"},"action":"empty"},"order":0,"id":"com.google.android.music.tv.HomeActivity-com.google.android.music","type":"app"},{"label":"Play Spiele","intent":{"component":{"packageName":"com.google.android.play.games","className":"com.google.android.apps.play.games.app.atv.features.home.HomeActivity"},"action":"android.intent.action.MAIN"},"order":0,"id":"com.google.android.apps.play.games.app.atv.features.home.HomeActivity-com.google.android.play.games","type":"app"},{"label":"Play Filme & Serien","intent":{"component":{"packageName":"com.google.android.videos","className":"com.google.android.videos.tv.presenter.activity.TvLauncherActivity"},"action":"empty"},"order":0,"id":"com.google.android.videos.tv.presenter.activity.TvLauncherActivity-com.google.android.videos","type":"app"},{"label":"Netflix","intent":{"component":{"packageName":"com.netflix.ninja","className":"com.netflix.ninja.MainActivity"},"action":"android.intent.action.MAIN"},"order":0,"id":"com.netflix.ninja.MainActivity-com.netflix.ninja","type":"app"},{"label":"Internet Browser","intent":{"component":{"packageName":"com.opera.sdk.example","className":"com.opera.sdk.example.OperaBrowserUiActivity"},"action":"android.intent.action.MAIN"},"order":0,"id":"com.opera.sdk.example.OperaBrowserUiActivity-com.opera.sdk.example","type":"app"},{"label":"Amazon Alexa","intent":{"component":{"packageName":"org.droidtv.amazonalexa","className":"org.droidtv.amazonalexa.wizard.AlexaWizardActivity"},"action":"android.intent.action.MAIN"},"order":0,"id":"org.droidtv.amazonalexa.wizard.AlexaWizardActivity-org.droidtv.amazonalexa","type":"app"},{"label":"TV-Guide","intent":{"component":{"packageName":"org.droidtv.channels","className":"org.droidtv.channels.ChannelsActivity"},"action":"android.intent.action.MAIN"},"order":0,"id":"org.droidtv.channels.ChannelsActivity-org.droidtv.channels","type":"app"},{"label":"Medien","intent":{"component":{"packageName":"org.droidtv.contentexplorer","className":"org.droidtv.contentexplorer.MainActivity"},"action":"android.intent.action.MAIN"},"order":0,"id":"org.droidtv.contentexplorer.MainActivity-org.droidtv.contentexplorer","type":"app"},{"label":"Demo-Menü","intent":{"component":{"packageName":"org.droidtv.demome","className":"org.droidtv.demome.DemoMeOptionsActivity"},"action":"empty"},"order":0,"id":"org.droidtv.demome.DemoMeOptionsActivity-org.droidtv.demome","type":"app"},{"label":"Sammlung von Philips TV","intent":{"component":{"packageName":"org.droidtv.nettv.market","className":"org.droidtv.nettv.market.MarketMainActivity"},"action":"android.intent.action.MAIN"},"order":0,"id":"org.droidtv.nettv.market.MarketMainActivity-org.droidtv.nettv.market","type":"app"},{"label":"Top Auswahl","intent":{"component":{"packageName":"org.droidtv.nettvrecommender","className":"org.droidtv.nettvrecommender.NetTvRecommenderMainActivity"},"action":"android.intent.action.MAIN"},"order":0,"id":"org.droidtv.nettvrecommender.NetTvRecommenderMainActivity-org.droidtv.nettvrecommender","type":"app"},{"label":"Fernsehen","intent":{"component":{"packageName":"org.droidtv.playtv","className":"org.droidtv.playtv.PlayTvActivity"},"action":"android.intent.action.MAIN"},"order":0,"id":"org.droidtv.playtv.PlayTvActivity-org.droidtv.playtv","type":"app"},{"label":"Asphalt Nitro","intent":{"component":{"packageName":"com.gameloft.android.HEP.GloftANHP","className":"com.gameloft.android.HEP.GloftANHP.MainActivity"},"action":"android.intent.action.MAIN"},"order":0,"id":"com.gameloft.android.HEP.GloftANHP.MainActivity-com.gameloft.android.HEP.GloftANHP","type":"game"},{"label":"ORF TVthek","intent":{"component":{"packageName":"com.nousguide.android.orftvthek","className":"com.nousguide.android.tvthek.fire.MainActivity"},"action":"android.intent.action.MAIN"},"order":0,"id":"com.nousguide.android.tvthek.fire.MainActivity-com.nousguide.android.orftvthek","type":"app"},{"label":"ZDFmediathek","intent":{"component":{"packageName":"com.zdf.android.mediathek","className":"com.zdf.android.mediathek.ui.splash.SplashActivity"},"action":"empty"},"order":0,"id":"com.zdf.android.mediathek.ui.splash.SplashActivity-com.zdf.android.mediathek","type":"app"},{"label":"kabel eins Doku","intent":{"component":{"packageName":"de.prosiebensat1digital.kabeleinsdoku","className":"de.prosiebensat1digital.seventv.view.SplashScreenActivity"},"action":"android.intent.action.MAIN"},"order":0,"id":"de.prosiebensat1digital.seventv.view.SplashScreenActivity-de.prosiebensat1digital.kabeleinsdoku","type":"app"},{"label":"ProSieben MAXX","intent":{"component":{"packageName":"de.prosiebensat1digital.prosiebenmaxx","className":"de.prosiebensat1digital.seventv.view.SplashScreenActivity"},"action":"android.intent.action.MAIN"},"order":0,"id":"de.prosiebensat1digital.seventv.view.SplashScreenActivity-de.prosiebensat1digital.prosiebenmaxx","type":"app"},{"label":"ARTE","intent":{"component":{"packageName":"org.droidtv.nettvapp1814","className":"com.zeasn.app.linux.MainActivity"},"action":"android.intent.action.MAIN"},"order":0,"id":"com.zeasn.app.linux.MainActivity-org.droidtv.nettvapp1814","type":"app"},{"label":"ARD Mediathek","intent":{"component":{"packageName":"org.droidtv.nettvapp3093","className":"com.zeasn.app.linux.MainActivity"},"action":"android.intent.action.MAIN"},"order":0,"id":"com.zeasn.app.linux.MainActivity-org.droidtv.nettvapp3093","type":"app"},{"label":"Flimmit","intent":{"component":{"packageName":"org.droidtv.nettvapp4470","className":"com.zeasn.app.linux.MainActivity"},"action":"android.intent.action.MAIN"},"order":0,"id":"com.zeasn.app.linux.MainActivity-org.droidtv.nettvapp4470","type":"app"},{"label":"Flimmit","intent":{"component":{"packageName":"org.droidtv.nettvapp5194","className":"org.droidtv.nettvapplication.NetTVActivity"},"action":"android.intent.action.MAIN"},"order":0,"id":"org.droidtv.nettvapplication.NetTVActivity-org.droidtv.nettvapp5194","type":"app"},{"label":"Kodi","intent":{"component":{"packageName":"org.xbmc.kodi","className":"org.xbmc.kodi.Splash"},"action":"android.intent.action.MAIN"},"order":0,"id":"org.xbmc.kodi.Splash-org.xbmc.kodi","type":"app"},{"label":"Solid Explorer","intent":{"component":{"packageName":"pl.solidexplorer2","className":"pl.solidexplorer.SolidExplorer"},"action":"android.intent.action.MAIN"},"order":0,"id":"pl.solidexplorer.SolidExplorer-pl.solidexplorer2","type":"app"},{"label":"Emby","intent":{"component":{"packageName":"tv.emby.embyatv","className":"tv.emby.embyatv.startup.StartupActivity"},"action":"android.intent.action.MAIN"},"order":0,"id":"tv.emby.embyatv.startup.StartupActivity-tv.emby.embyatv","type":"app"},{"label":"Einstellungen","intent":{"component":{"packageName":"org.droidtv.settings","className":"org.droidtv.settings.setupmenu.SetupMenuActivity"},"action":"android.intent.action.MAIN"},"order":0,"id":"org.droidtv.settings.setupmenu.SetupMenuActivity-org.droidtv.settings","type":"app"},{"label":"Sender installieren","intent":{"component":{"packageName":"org.droidtv.settings","className":"org.droidtv.settings.setupmenu.ChannelSettingActivity"},"action":"android.intent.action.MAIN"},"order":0,"id":"org.droidtv.settings.setupmenu.ChannelSettingActivity-org.droidtv.settings","type":"app"},{"label":"Wie Sie...","intent":{"component":{"packageName":"org.droidtv.eum","className":"org.droidtv.eum.onehelp.menu.HowToLauncherActivity"},"action":"android.intent.action.MAIN"},"order":0,"id":"org.droidtv.eum.onehelp.menu.HowToLauncherActivity-org.droidtv.eum","type":"app"},{"label":"Kabellos und Netzwerke","intent":{"component":{"packageName":"org.droidtv.settings","className":"org.droidtv.settings.setupmenu.WirelessAndNetworkSettingsActivity"},"action":"android.intent.action.MAIN"},"order":0,"id":"org.droidtv.settings.setupmenu.WirelessAndNetworkSettingsActivity-org.droidtv.settings","type":"app"},{"label":"Apps verwalten","intent":{"component":{"packageName":"com.android.tv.settings","className":"com.android.tv.settings.device.apps.AppsActivity"},"action":"empty"},"order":0,"id":"com.android.tv.settings.device.apps.AppsActivity-com.android.tv.settings","type":"app"},{"label":"Hilfe","intent":{"component":{"packageName":"org.droidtv.eum","className":"org.droidtv.eum.onehelp.menu.OneHelpActivity"},"action":"android.intent.action.MAIN"},"order":0,"id":"org.droidtv.eum.onehelp.menu.OneHelpActivity-org.droidtv.eum","type":"app"},{"label":"Software aktualisieren","intent":{"component":{"packageName":"org.droidtv.settings","className":"org.droidtv.settings.setupmenu.UpdateSWSettingsActivity"},"action":"android.intent.action.MAIN"},"order":0,"id":"org.droidtv.settings.setupmenu.UpdateSWSettingsActivity-org.droidtv.settings","type":"app"}]}
`

Thank you

**Comment by popy2k14** [comment]
@eslavnov Can you please guide me in the right direcion?

Thanks a lot

**Comment by eslavnov** [comment]
Hey @popy2k14, there seems indeed to be something wrong with the `launch_app`, I'll take a look today. Thanks for reporting this issue!

**Comment by popy2k14** [comment]
@eslavnov thx for confirming, take your time.
I am here to test 🙂

Thx

**Comment by eslavnov** [comment]
@popy2k14 I've just pushed a fixed version, it works fine for me on Pie. Can you give it a try? Thanks!

**Comment by popy2k14** [comment]
@eslavnov Thanks for the fast fix. All is working as expected now with new version.
Issue can be closed.
Thank you
