### ISSUE TITLE
[BUG] It is  Philips 49PUS7150 (2015) supported?

### ISSUE THREAD

**Issue by QSKONE** [eslavnov/pylips#18]
Hi , 
It is  supported Philips 49PUS7150 (late 2015) Android TV 5.1? 
Because python not running. 
```
ntb@ntb:~/Plocha/pylips-master$ python pylips.py
  File "pylips.py", line 42
    return print("Config file", ini_file, "not found")
               ^
SyntaxError: invalid syntax
```

**Comment by eslavnov** [comment]
Try running it with `python3`

**Comment by QSKONE** [comment]
Hi , I must detete mqtt line 15 and them script works. Thanks you very much. 
```
ntb@ntb:~/Plocha/pylips-master$ python3 pylips.py
Traceback (most recent call last):
  File "pylips.py", line 15, in <module>
    import paho.mqtt.client as mqttc
ModuleNotFoundError: No module named 'paho'
```

**Comment by eslavnov** [comment]
@QSKONE run `pip3 install -r requirements.txt` then this line will work.

On some systems `pip` and `python` link to Python 3, but on others (such as yours) they link to Python 2, so you have to use `pip3` and `python3` instead.
