### ISSUE TITLE
Launching Apps - adding to documentation

### ISSUE THREAD

**Issue by Mic-M** [eslavnov/pylips#25]
Many thanks for your work! I am currently using it for the IOT system ioBroker since there is a plugin which needs some enhancements and I guess your Python code is awesome and should be adopted.
See https://forum.iobroker.net/topic/8791/aufruf-philips-tv-v0-1-0-testen (in German).

I would wish to add some more examples for launching apps to the documentation. Finally, all does follow the same syntax and we just need to use "Activities current (GET)" to get the current application data and then change the template accordingly.

`Amazon Prime Video:
{"id":"com.amazon.amazonvideo.livingroom","order":0,"intent":{"action":"Intent{act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10000000 pkg=com.amazon.amazonvideo.livingroom }","component":{"packageName":"com.amazon.amazonvideo.livingroom","className":"com.amazon.ignition.IgnitionActivity"}},"label":"Prime Video"}

Kodi
{"id":"org.xbmc.kodi","order":0,"intent":{"action":"Intent{act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10000000 pkg=org.xbmc.kodi }","component":{"packageName":"org.xbmc.kodi","className":"org.xbmc.kodi.Splash"}},"label":"Kodi"}

Netflix
{"id":"com.netflix.ninja","order":0,"intent":{"action":"Intent{act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10000000 pkg=com.netflix.ninja }","component":{"packageName":"com.netflix.ninja","className":"com.netflix.ninja.MainActivity"}},"label":"Netflix"}

YouTube
{"id":"com.google.android.apps.youtube.tv.activity.ShellActivity-com.google.android.youtube.tv","order":0,"intent":{"action":"Intent{act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10000000 pkg=com.google.android.youtube.tv cmp=com.google.android.youtube.tv/com.google.android.apps.youtube.tv.activity.ShellActivity }","component":{"packageName":"com.google.android.youtube.tv","className":"com.google.android.apps.youtube.tv.activity.ShellActivity"}},"label":"YouTube"}`

**Comment by eslavnov** [comment]
Thanks, man! I will add these examples next time I push an update!

**Comment by busshi** [comment]
For those who have Molotov :

'{"id":"tv.molotov.app","order":0,"intent":{"action":"Intent{act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10000000 pkg=tv.molotov.app }","component":{"packageName":"tv.molotov.app","className":"tv.molotov.android.ui.common.splash.SplashActivity"}},"label":"Molotov"}'
