### ISSUE TITLE
[FEAT] Allow self signed SSL certificates

### ISSUE THREAD

**Issue by timbru31** [eslavnov/pylips#26]
**Is your feature request related to a problem? Please describe.**
While mqtt over TLS is supported, it's missing the possibility to configure a custom SSL/TLS certificate.

**Describe the solution you'd like**
I'd like to have a config option where I can configure my broker SSL cert.

**Describe alternatives you've considered**
n/a

**Additional context**
paho-mqtt supports these options in the `tls_set()` function. See https://pypi.org/project/paho-mqtt/#option-functions

(my example setup with `self.mqtt.tls_set("/opt/pylips/mosquitto.crt")` works)

**Comment by eslavnov** [comment]
Thanks, that's a good idea! I will add it in the next couple of days.

**Comment by timbru31** [comment]
Great - thanks a lot. Awesome project btw 🎉
