### ISSUE TITLE
[FEAT] Add input switch commands

### ISSUE THREAD

**Issue by FezVrasta** [eslavnov/Pylips#3]
**Is your feature request related to a problem? Please describe.**
I'd like to have a way to switch between HDMI inputs

**Describe the solution you'd like**
I'd be surprised if such API was not available, but I don't have enough experience to tell.

**Comment by eslavnov** [comment]
The method that used to work in old API does not work anymore and the Philips mobile app does not switch inputs either, so I am 99% sure it's impossible with the current API.

As a workaround, you can try this small script to switch sources for Android TVs: https://github.com/eslavnov/android-tv-remote

**Comment by FezVrasta** [comment]
Great thanks!
