### ISSUE TITLE
[FEAT] Add textentry to documentation

### ISSUE THREAD

**Issue by lucasvdh** [eslavnov/pylips#32]
Some Android TVs appear to support text input via the Jointspace api.

I'm not a 100% sure about this but the system response seems to suggest it:
```json
{
  "featuring": {
    "jsonfeatures": {
      "textentry": [
        "context_based",
        "initial_string_available",
        "editor_info_available"
      ]
    }
  }
}
```
If you look at for example how the recordings feature is returned in the jsonfeatures object:
```json
{
  "featuring": {
    "jsonfeatures": {
      "recordings": [
        "List",
        "Schedule",
        "Manage"
      ]
    }
  }
}
```
This references that the `recordings` feature has a `List` endpoint. And the `recordings` feature does indeed have a `/recordings/list` endpoint.

If the `textentry` feature follows the same logic this should be available at `/textentry` or something like `/textentry/context_based` or `/textentry/editor_info_available`. However I haven't been able to figure out which endpoints this feature uses or when its available, most likely only when an input field is selected.

As far as I know the Philips Remote App doesn't offer any text input options, even though my tv appears to support it, so its a tricky one to reverse engineer.

Any thoughts?

**Comment by eslavnov** [comment]
Hey, I think that this endpoint might be used for search (I remember seeing something like that in the mobile app), but I don't have access to a TV right now to test. I'll take a look in a week or two and will report back.

**Comment by eslavnov** [comment]
Ok, so I've tested the search in the Phillips mobile app, however, it does not use this endpoint... 

I'll try to investigate more, but for now I unfortunately have no clue where the `textentry` enpoint is used...

**Comment by eslavnov** [comment]
Closing the issue for now since I don't have any more ideas to test. Will re-open when there is any new info/ideas available.

**Comment by zierka** [comment]
The text entry endpoint is at POST `/input/textentry` and the body is:

```
{"currentstring" : "<the full string you want to pass to the textfield>"}
```

It looks like it works only if the POST `/notifychange` API returns that `"textentry":"requested"`.

Looks like it works for textfields where the builtin android keyboard is showing on the TV. There are apps that do not use the standard android keyboard (Netflix, HBO GO), so text input did not work there.

That's what I know for now. I checked this by inspecting the calls the Philips Remote iOS app is doing.

**Comment by eslavnov** [comment]
@zierka, thank you for sharing this! I'll check if it's indeed the case and will update the docs if it works!

**Comment by evgsil** [comment]
FYI one more useful feature is to send chars one by one to POST /input/key
with the body {"unicode" : "A"}

Works pretty well on input fields for my non-Android TV (2019)

**Comment by evgsil** [comment]
Also you could use POST /input/pointer

**Comment by zierka** [comment]
`/input/textentry`

```
{
  "currentstring" : "<the full string you want to pass to the textfield>",
  "action_id": "IME_ACTION_SEARCH"
}
```

This also submits the input.
