### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by pingloss** [eslavnov/pylips#34]
Hi,

Initial communication has completed and has populated settings.ini however attempting to issue a command fails returning back a message that ‘The request requires authentication’.

I’ve also tried issuing the command while also adding the user and pass variables but with the same response back.

python3 ./pylips.py --command volume
Sending GET request to https://192.168.1.71:1926/6/audio/volume
Request sent!
<html>
<head>
   <title>Status page</title>
</head>
<body style="font-family: sans-serif;">
<p style="font-size: 1.2em;font-weight: bold;margin: 1em 0px;">Unauthorized</p>
<p>The request requires user authentication</p>
<p>You can get technical details <a href="http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10.4.2">here</a>.<br>
Please continue your visit at our <a href="/">home page</a>.
</p>
</body>
</html>

**Comment by eslavnov** [comment]
Hi,
That's weird, could you please share with me your settings.ini so I can try to replicate it? I am on a beach right now with no technology whatsoever (sending this message by a postal pigeon), so I'll take a look at this issue next week once I am back. Thanks!

**Comment by pingloss** [comment]
Hi there,

Here’s the contents of the settings.ini file

[DEFAULT]
verbose = True
mqtt_listen = False
mqtt_update = False
num_retries = 3
[DEFAULT]
update_interval = 3

[TV]
host = 192.168.1.71
port = 1926
apiv = 6
user = jvLMtCJZU1Vsvi3T
pass = 9b83ccb41173a44d8741d5e207ff19272bdefd5762fff11b41b1a259009b172a
protocol = https://

[MQTT]
host =
port =
user =
pass =
tls = False
cert_path =
topic_pylips =
topic_status =

Thanks,
Simon

**Comment by eslavnov** [comment]
Hey Simon,

I've just checked using the same settings and it works fine for me. The only thing that I've noticed is that you have `[DEFAULT]` specified twice for some reason in your settings.ini, but it should be there only once in the very beginning of the file. Maybe try replacing your settings.ini with the original one and try pairing again?

**Comment by Darkensen** [comment]
Hello, I have the same problem.
Here my settings.ini :
[DEFAULT]
verbose = True
mqtt_listen = False
mqtt_update = False
num_retries = 3
update_interval = 3

[TV]
host = 192.168.1.66
port = 1926
apiv = 6
user = BqjadVW74Mfa43KR
pass = 67e05d9b3dbd09ba90dc3efe0223fb473842e6f052aac3593d73e2fe8aa46ad1
protocol = https://

[MQTT]
host = 
port = 
user = 
pass = 
tls = False
cert_path = 
topic_pylips = 
topic_status = 

And i get the same problem when running manualy :

python3 pylips.py --user BqjadVW74Mfa43KR --pass 67e05d9b3dbd09ba90dc3efe0223fb473842e6f052aac3593d73e2fe8aa46ad1 --host 192.168.1.66 --command powerstate
Sending GET request to https://192.168.1.66:1926/6/powerstate
Request sent!
<html>
<head>
   <title>Status page</title>
</head>
<body style="font-family: sans-serif;">
<p style="font-size: 1.2em;font-weight: bold;margin: 1em 0px;">Unauthorized</p>
<p>The request requires user authentication</p>
<p>You can get technical details <a href="http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10.4.2">here</a>.<br>
Please continue your visit at our <a href="/">home page</a>.
</p>
</body>
</html>


i tried to remove the user/pass in settings and repair, but same problem.

PS : Thanks for this great work ! I work with Jeedom to control my TV

**Comment by eslavnov** [comment]
@Darkensen Thank you for reporting this! I am a bit lost since I can not replicate this issue, so I will need your help troubleshooting it.

First of all, can you please try calling an endpoint with cURL using the username and password that the pylips generated for you? The general syntax is: 
`curl -X GET --digest --insecure -u %username%:%password% https://%ip_address%:1926/6/%endpoint%`

(curl should be pre-installed in *NIX systems, but you'll have to install it manually for Windows, if I remember everything correctly)

**Comment by Darkensen** [comment]
Same

curl -X GET --digest --insecure -u Q1EoRgPF09zfKhnC:adf3d99f45cc1c247e201c1732681b5f6e677cb298d6c4df82dfefb44505b00 https://192.168.1.66:1926/6/powerstate
<html>
<head>
   <title>Status page</title>
</head>
<body style="font-family: sans-serif;">
<p style="font-size: 1.2em;font-weight: bold;margin: 1em 0px;">Unauthorized</p>
<p>The request requires user authentication</p>
<p>You can get technical details <a href="http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10.4.2">here</a>.<br>
Please continue your visit at our <a href="/">home page</a>.
</p>
</body>
</html>

**Comment by eslavnov** [comment]
Thanks for the quick reply! Looks like the credentials are wrong for some reason... I remember indeed changing the pairing part a bit some time ago and, perhaps, I broke something in the process... Still weird, because I've repaired my TV with the new versions and they work fine for me. I guess, we are hitting some kind of an edge case...

You've mentioned that v0.4 work for you - did you test it recently or in the past?

**Comment by Darkensen** [comment]
Just test now, still works

**Comment by eslavnov** [comment]
Does v0.4 work with the new credentials or only with the ones you get by pairing using v0.4?

**Comment by Darkensen** [comment]
Hello, The 0.4 work with both

**Comment by eslavnov** [comment]
Wow, that does not make any sense... Just to make sure I understand you correctly:
1) you pair using the latest version
2) using these credentials you get 'unauthorized' error in pylips (latest version) and curl
3) using these credentials in v0.4 you get a correct response

Or did I misunderstood something?

**Comment by Darkensen** [comment]
I find my mistake, I don't know why but the password I used was shrinked when I do the copy/past to the settings file.
Everything works now ...
Sorry for your time ...

Regards

**Comment by eslavnov** [comment]
No problem, glad to hear that it works!
