### ISSUE TITLE
Timer set up

### ISSUE THREAD

**Issue by busshi** [eslavnov/pylips#37]
Hello,

Nice job with the documentation and everything else. I’m trying to set up the timer. I can get info with : 
"menuitems/settings/current -d {\"nodes\":[{\"nodeid\":2131230835}]}"

It returns : 
"values":[{"value":{"Nodeid":2131230835,"Controllable":true,"Available":true,"string_id":"Arrêt programmé","data":{"value":0}}}],"version":0}

So I have the good nodeid for the timer and it is controllable.
If I change with the remote the timer to power off the value changes with the previous command again. But if I send the following command, I got no error but the timer is not set up !!

menuitems/settings/update -d {\"values\":[{\"value\":{\"Nodeid\":2131230835,\"Controllable\":true,\"Available\":true,\"data\":{\"value\":40}}}]}"

Value=40 for 40 minutes before shutting down the TV...

How can I fix this ?

Thanks.

**Comment by eslavnov** [comment]
Hi!

I think that not all nodes with the `"Controllable":true` attribute can be actually controlled through the API - I remember having the same issue with some other endpoint... Your request seems correct to me, so probably it's not supported. 

I'll check this endpoint with my TV in the coming days and will report back if it works for me.

**Comment by eslavnov** [comment]
Closing since I was not able to make it work. Feel free to reopen if somebody figures out how to use it.
