### ISSUE TITLE
[BUG] Can't launch Netflix (Philips TV POS9002)

### ISSUE THREAD

**Issue by CodySummers** [eslavnov/pylips#40]
**Describe the bug**
Might be a new user error, when I try the example code to launch netflix, amazon prime etc I can't. 

This is the message I get back when using it.

Traceback (most recent call last):
  File "pylips.py", line 453, in <module>
    pylips = Pylips(os.path.dirname(os.path.realpath(__file__))+"/settings.ini")
  File "pylips.py", line 109, in __init__
    self.run_command(args.command,body, self.verbose)
  File "pylips.py", line 311, in run_command
    return self.post(self.available_commands["post"][command]["path"], body,verbose, callback)
  File "pylips.py", line 265, in post
    body = json.loads(body)
  File "C:\Python34\lib\json\__init__.py", line 318, in loads
    return _default_decoder.decode(s)
  File "C:\Python34\lib\json\decoder.py", line 343, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python34\lib\json\decoder.py", line 361, in raw_decode
    raise ValueError(errmsg("Expecting value", s, err.value)) from None
ValueError: Expecting value: line 1 column 1 (char 0)

**To Reproduce**
Use this in CMD:

python pylips.py --command launch_app --body '{"id":"com.amazon.amazonvideo.livingroom","order":0,"intent":{"action":"Intent{act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10000000 pkg=com.amazon.amazonvideo.livingroom }","component":{"packageName":"com.amazon.amazonvideo.livingroom","className":"com.amazon.ignition.IgnitionActivity"}},"label":"Prime Video"}'

**Expected behavior**
Opens Amazon Prime

**Screenshots**

**Additional context**
Probably a new user error.

**Comment by eslavnov** [comment]
Hi, thanks for reporting this. Do other commands work for you (like volume or power off, for example)?

**Comment by eslavnov** [comment]
Yeah, turning on after off is indeed a deep sleep issue.
Could you please locate line 265 in Pylips.py (body = json.loads(body)) and add `print(body)` before it? Then try to launch Amazon again and share the output here. Thanks!

**Comment by CodySummers** [comment]
This is what I get with print added.

'{id:com.amazon.amazonvideo.livingroom,order:0,intent:{action:Intent{act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10000000 pkg=com.amazon.amazonvideo.livingroom },component:{packageName:com.amazon.amazonvideo.livingroom,className:com.amazon.ignition.IgnitionActivity}},label:Prime Video}'
Traceback (most recent call last):
  File "pylips.py", line 453, in <module>
    pylips = Pylips(os.path.dirname(os.path.realpath(__file__))+"/settings.ini")
  File "pylips.py", line 109, in __init__
    self.run_command(args.command,body, self.verbose)
  File "pylips.py", line 311, in run_command
    return self.post(self.available_commands["post"][command]["path"], body,verbose, callback)
  File "pylips.py", line 265, in post
    print(body) (body = json.loads(body))
  File "C:\Python34\lib\json\__init__.py", line 318, in loads
    return _default_decoder.decode(s)
  File "C:\Python34\lib\json\decoder.py", line 343, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python34\lib\json\decoder.py", line 361, in raw_decode
    raise ValueError(errmsg("Expecting value", s, err.value)) from None
ValueError: Expecting value: line 1 column 1 (char 0)

**Comment by eslavnov** [comment]
Your body argument is not properly formatted (`id:com.amazon.amazonvideo.livingroom` instead of `"id":"com.amazon.amazonvideo.livingroom"`, and so on...). This works on my TV:

`python pylips.py --command launch_app --body '{"id":"com.amazon.amazonvideo.livingroom","order":0,"intent":{"action":"Intent{act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10000000 pkg=com.amazon.amazonvideo.livingroom }","component":{"packageName":"com.amazon.amazonvideo.livingroom","className":"com.amazon.ignition.IgnitionActivity"}},"label":"Prime Video"}`

**Comment by CodySummers** [comment]
What I type in has the `"` the version without the speechmarks get printed when I add `print(body)` to line 265.

I copied and pasted your code snippet to double check and got the same error:

```
Traceback (most recent call last):
  File "pylips.py", line 453, in <module>
    pylips = Pylips(os.path.dirname(os.path.realpath(__file__))+"/settings.ini")
  File "pylips.py", line 109, in __init__
    self.run_command(args.command,body, self.verbose)
  File "pylips.py", line 311, in run_command
    return self.post(self.available_commands["post"][command]["path"], body,verbose, callback)
  File "pylips.py", line 265, in post
    body = json.loads(body)
  File "C:\Python34\lib\json\__init__.py", line 318, in loads
    return _default_decoder.decode(s)
  File "C:\Python34\lib\json\decoder.py", line 343, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python34\lib\json\decoder.py", line 361, in raw_decode
    raise ValueError(errmsg("Expecting value", s, err.value)) from None
ValueError: Expecting value: line 1 column 1 (char 0)
```

Might just be a slight API variation, thanks for your help.
