### ISSUE TITLE
[FEAT]Make a pip package

### ISSUE THREAD

**Issue by HydrelioxGitHub** [eslavnov/pylips#48]
**Is your feature request related to a problem? Please describe.**
I use Home Assitant, and I would really like to add your work in this eco system. It will allow a lot of user to easily control the Ambilight light as a classic connected light and some other great feature.

**Describe the solution you'd like**
I have some basics skills in Python and I can work on the integration in Home Assistant but the software require a pip library to make it easy. (Maybe I can use directly this github repository but I have to look further to see if it possible). 

**Describe alternatives you've considered**
I can make another repo from scratch and make the library from scratch based on your work. But it could be difficult for me to reflect any update made by you.

**Additional context**
I'm open to any idea that could lead to integrate TV in Home Assistant. I can provide some help if it's not beyond my skills in Python.

**Comment by eslavnov** [comment]
Hey @HydrelioxGitHub,

If your goal is to have integration with Home Assistant, I can suggest this repo: https://github.com/nstrelow/ha_philips_android_tv

and for ambilight in particular this one:
https://github.com/jomwells/ambilights

When Pylips has just started it had some unique features (such as ambilight+hue control), but nowadays 99% (if not 100%) of Pylips features are supported by those two repos (I was in contact with the owners of these repos at some point).

Both @nstrelow and @jomwells do an amazing job supporting their Home Assistant components, I highly recommend to check them out.
