### ISSUE TITLE
[BUG] return print('Error', r.json())

### ISSUE THREAD

**Issue by jdschuitemaker** [eslavnov/pylips#5]
**Describe the bug**
I am seeing the error below when I try to run a pylips command

`  File "pylips.py", line 48
    return print('Error', r.json())`

I notice that that in line 44 there is a request to an ip address (172.168.201.11) that is not responding. Shouldn't this be the ip address of your TV instead?

**To Reproduce**
run the following command:
`python pylips.py --host <ip address> --user <user code> --pass <pass code> --command powerstate
`

**Expected behavior**
JSON reflecting the result of the powerstate command

**Comment by jdschuitemaker** [comment]
It seems that the following command is not supported in Python (?). I am using version 2.7.13

`return print("some text")`

After removing the "return" from that line, it starts working.

**Comment by eslavnov** [comment]
> I notice that that in line 44 there is a request to an ip address (172.168.201.11) that is not responding. Shouldn't this be the ip address of your TV instead?

Fixed, thank you!

> It seems that the following command is not supported in Python (?). I am using version 2.7.13
You should be using Python 3 as stated in the "Prerequisites" section in the readme.

> python3
