### ISSUE TITLE
[FEAT] Installation failed - Dependency pycrypto - Change in requirements.txt

### ISSUE THREAD

**Issue by daen2424** [eslavnov/pylips#53]
Installing requirements from "requirements.txt" was not possible.
The package "pycrypto" failed to install.
Installing Visual Studio C++ Build Tools does not change anything.

At long last i installed the package "pycryptodome":
$pip install pycryptodome
This package worked for me and the TV "Philips 65PUS6704/12" is working (Not fully tested yet).

**Comment by eslavnov** [comment]
Thanks for the report! Looks like indeed pycrypto has some issues on Windows, I'll test your suggestion and will update the requirements.txt if everything works!

**Comment by eslavnov** [comment]
Fixed by #54
