### ISSUE TITLE
[FEAT] send text to TV

### ISSUE THREAD

**Issue by busshi** [eslavnov/pylips#56]
Hello, I would like to send notifications on the TV screen. It is possible because there is a command to send text but it doesn’t work for me.

I have an Echo device and if I use the Alexa app in the TV to pair both devices (Alexa and TV) I can see notifications on the screen when I turn the TV off for example, the TV writes something like Goodbye on the screen. It could be very useful for those who do home automation (alarm for example...).

Does somebody know how this command works ?

I don’t know how to use a sniffer to catch the trafic but I think it is possible. If someone could help for that... Thanks

**Comment by popy2k14** [comment]
I am using "Notifications for Android TV" see the apropriat fhem thread here: https://forum.fhem.de/index.php?topic=83065.0

With this i am sending notifications to my android tv since a xear without any issue.

**Comment by busshi** [comment]
Ok i am gonna try this. I had an Android phone before and I used newtifry to get notifications from pushingbox service (1000 free requests per day!!!). I will try your app...

**Comment by popy2k14** [comment]
The App i mention works local, without any cloud :-)

**Comment by busshi** [comment]
Waow really nice but is it possible to send notifications with url ? Or I have to own an Android phone for this to work ? I want to send notifications from my raspberry when a sensor triggers...

**Comment by popy2k14** [comment]
yes! My local installation of fhem (running on rpi) is sending local requests to the tv ip address over my local network. Please see the source code of the fhem module here https://svn.fhem.de/trac/browser/trunk/fhem/FHEM/37_NotifyAndroidTV.pm

I think you can figure out how to "curl" local requests to send a notification :-)

**Comment by busshi** [comment]
Thanks for the informations. I installed this app fine, but at the end they say I have to continue setting up in an android phone or tablet. I don’t have any of this ! I have the option to manually set up, they says to go at this url : http://IP_TV but nothing appears...
I try this url from the TV browser, same error... So I look into the code to find a way to curl : I try
curl -X POST http://IP:7676 with option -d {value} to send a test notification but nothin appear (no error with curl but nothing appear on the TV).
Do you have any idea ? What am I doing wrong ?

**Comment by busshi** [comment]
So apparently it is not possible this app without having an Android mobile or tablet according to the developper. I have to find another way...

**Comment by popy2k14** [comment]
Take a look at PipUp:

https://play.google.com/store/apps/details?id=nl.rogro82.pipup
https://github.com/rogro82/pipup
https://forum.fhem.de/index.php/topic,106363.0.html

Good luck

**Comment by busshi** [comment]
Nice Popip does the job very well ! 👌 Thanks a lot

**Comment by popy2k14** [comment]
Nice that it's working for you!
