### ISSUE TITLE
[BUG] Ambilight+Hue commands not work (Philips 55PUS7304)

### ISSUE THREAD

**Issue by nikosillo** [eslavnov/pylips#60]
Hello!
First congratulate you for this great script. The second I apologize for my English, I must use Google Translate.
I am trying to generate a switch by mqtt to be able to turn the Ambilight + Hue on and off on the 55PUS7304 and be able to integrate this feature into my home automation center.
The Philips Remote application connects relatively well with the TV (it has disconnection failures and the ambilight bridge settings do not synchronize with the TV) but the turning on and off of both Ambilight and Ambilight-Hue, once configured on the TV, work well .

This is the value returned by mqtt:
{"powerstate": "On", "volume": 20, "muted": false, "cur_app": "uk.co.freeview.onnow", "ambilight": {"styleName": "FOLLOW_VIDEO", "isExpert ": false," menuSetting ":" NATURAL "," stringValue ":" Natural "}," ambihue ": 5}

I don't understand that value 5 in Ambihue. If I turn off the ambihue with the app or from the TV, it does not change.

I deactivate the mqtt in settings.ini and now I do tests with the readme commands:

For status

```
pi@DiyHuePi:/pylips $ sudo python3 pylips.py --host 172.16.10.11 --user qqjKm8W9ub5RCrW3 --pass 73ad38878df23d1689b9fc0cfaec9c1f5067f30b0fbf56ce1e609b76c0e47884 --command ambihue_status
Sending POST request to https://172.16.10.11:1926/6/menuitems/settings/current
Request sent!
{"values":[{"value":{"Nodeid":2131230774,"Controllable":true,"Available":false,"string_id":"Brillo de la parte inferior","data":{"value":5}}}],"version":1581773617053}
```

For Ambi+Hue on
```
pi@DiyHuePi:/pylips $ sudo python3 pylips.py --host 172.16.10.11 --user qqjKm8W9ub5RCrW3 --pass 73ad38878df23d1689b9fc0cfaec9c1f5067f30b0fbf56ce1e609b76c0e47884 --command ambihue_on
Sending POST request to https://172.16.10.11:1926/6/menuitems/settings/update
Request sent!
{"response": "OK"}
```
For Ambi+Hue off

```
pi@DiyHuePi:/pylips $ sudo python3 pylips.py --host 172.16.10.11 --user qqjKm8W9ub5RCrW3 --pass 73ad38878df23d1689b9fc0cfaec9c1f5067f30b0fbf56ce1e609b76c0e47884 --command ambihue_off
Sending POST request to https://172.16.10.11:1926/6/menuitems/settings/update
Request sent!
{"response": "OK"}
```
Nothing happens. Only change in status, the value
"version": 1581773617053
that its number is increasing (54, 55, 56 ...)

These are the values offered in the browser https://172.16.10.11:1926/6/system
`{"notifyChange":"http","menulanguage":"Spanish","name":"55PUS7304\/12","country":"Spain","serialnumber_encrypted":"s53vNo\/gABVJXbfA4wAP0w3Rsy6YcS6g5dtYQLWw76E=\n","softwareversion_encrypted":"wuIstBMd8\/WsNDlcly9T4EeYPOI+GJrK08kDdVFC3b7a17YUuVYF7Er6ZBA2Unom\n","model_encrypted":"IHrF2HY3A1IcuZYPrd02ozA9ilATGZQR\/H6ictzWVcI=\n","deviceid_encrypted":"vxw2iJBhiCSM5Ig5H9\/jCwnAbzSbE\/Twt5cRWtEwasI=\n","nettvversion":"8.2.0","epgsource":"no_epg","api_version":{"Major":6,"Minor":1,"Patch":0},"featuring":{"jsonfeatures":{"editfavorites":["TVChannels","SatChannels"],"recordings":["List","Schedule","Manage"],"ambilight":["LoungeLight","Hue","Ambilight","HueStreaming"],"menuitems":["Setup_Menu"],"textentry":["not_available"],"applications":["TV_Apps","TV_Games","TV_Settings"],"pointer":["not_available"],"inputkey":["key"],"activities":["intent"],"channels":["preset_string"],"mappings":["server_mapping"]},"systemfeatures":{"tvtype":"consumer","content":["dmr","pvr"],"tvsearch":"intent","pairing_type":"digest_auth_pairing","secured_transport":"true","companion_screen":"true"}},"os_type":"MSAF_2019_P"}`

Any ideas or help? Any test I can do, I offer my model to test
Thx

**Comment by eslavnov** [comment]
Hey @nikosillo,

Thanks for your feedback! It looks like your TV is using some other NodeId for Ambilight+hue, because `ambihue_status` returns different data for me:
`{"values":[{"value":{"Nodeid":2131230774,"Controllable":true,"Available":true,"string_id":"Switch on","data":{"value":false}}}],"version":0}`

Could you please run Pylips with the following args?
`--command get --path 'menuitems/settings/structure' --verbose True > settings_dump.txt`

This should create a file `settings_dump.txt` with a menu structure for your TV. Please share this file with me and hopefully I'll be able to add support for your particular TV.

Thanks!

**Comment by nikosillo** [comment]
Thank you very much, I would really appreciate it
I don't know if the data in that file is sensitive, I send it to you by email. It would really be great to be able to support this model, although it is strange, I thought it was a more common model

**Comment by PostSven** [comment]
I happen to have the same issue, i found that the node id is actually different

{"node_id":2131230776,"type":"PARENT_NODE","string_id":"org.droidtv.ui.strings.R.string.MAIN_AMBILIGHT_PLUS_HUE","context":"ambilight_hue_menu","data":{"nodes":[{"node_id":2131230777,"type":"PARENT_NODE","string_id":"org.droidtv.ui.strings.R.string.MAIN_AMBILIGHT_HUE_CONFIGURE","context":"ambilight_hue_wizard","data":{}},{"node_id":2131230778,"context":"ambilight_hue_off","data":{},"type":"TOGGLE_NODE"},

**Comment by eslavnov** [comment]
Hi @PostSven,

Thanks for sharing the info! Indeed, the node_ids are different, here are the ones that work for this model:
1) Should turn ambilight off:
python3 pylips.py --command post --path menuitems/settings/update --body '{ "values": [{ "value": { "Nodeid": 2131230766, "Controllable": true, "Available": true, "data": { "activenode_id": 2131230767 } } }] }'
2) Should turn ambilight on:
python3 pylips.py --command post --path menuitems/settings/update --body '{ "values": [{ "value": { "Nodeid": 2131230766, "Controllable": true, "Available": true, "data": { "activenode_id": 2131230768 } } }] }'
3) Should turn ambilight+hue on:
python3 pylips.py --command post --path menuitems/settings/update --body '{ "values": [{ "value": { "Nodeid": 2131230778, "Controllable": false, "Available": true, "data": { "value": true } } }] }'
4) Should turn ambilight+hue off:
python3 pylips.py --command post --path menuitems/settings/update --body '{ "values": [{ "value": { "Nodeid": 2131230778, "Controllable": false, "Available": true, "data": { "value": false } } }] }'
5) Should return ambilight+hue status:
python3 pylips.py --command post --path menuitems/settings/current --body '{ "nodes": [{ "nodeid": 2131230778 }] }'

Unfortunately, I don't have the time to make a proper fix for Pylips now ('job searching + corona pandemic' is not a good combo....), but I will fix it as soon as things become less hectic for me. For now, please use the manual commands above. Thanks again!

**Comment by ridwancc** [comment]
hi there, im having trouble turning on and off the ambilight and ambilight hue on the tv. Just does not work. If i try to return status of ambilight hue get an empty response. Heres my dump file. Are you able to help?

Sending GET request to http://192.168.1.83:1925/6/menuitems/settings/structure
Request sent!
{
	"node": {
		"node_id": 1,
		"type": "PARENT_NODE",
		"string_id": "MLM_PHM_KEY_ID_AMBIL_L15",
		"icon": null,
		"context": "ambilight",
		"data": {
			"nodes": [
				{
					"node_id": 100,
					"type": "PARENT_NODE",
					"string_id": "MLM_PHM_KEY_MAIN_AMBILIGHT_STYLE",
					"icon": null,
					"context": "ambilight_style",
					"data": {
						"nodes": [
							{
								"node_id": 110,
								"type": "PARENT_NODE",
								"string_id": "MLM_PHM_KEY_MAIN_AMBILIGHT_STYLE_OFF",
								"icon": null,
								"context": "ambilight_off",
								"data": {

								}
							},
							{
								"node_id": 120,
								"type": "LIST_NODE",
								"string_id": "MLM_PHM_KEY_MAIN_FOLLOW_VIDEO",
								"icon": null,
								"context": "ambilight_follow_video",
								"data": {
									"enums": [
										{
											"enum_id": 121,
											"string_id": "MLM_PHM_KEY_MAIN_AMBILIGHT_STANDARD"
										},
										{
											"enum_id": 122,
											"string_id": "MLM_PHM_KEY_MAIN_AMBILIGHT_NATURAL"
										},
										{
											"enum_id": 123,
											"string_id": "MLM_PHM_KEY_ID_AMB_MODE4_2K18"
										},
										{
											"enum_id": 124,
											"string_id": "MLM_PHM_KEY_MAIN_AMBILIGHT_VIVID"
										},
										{
											"enum_id": 125,
											"string_id": "MLM_PHM_KEY_MAIN_AMBILIGHT_GAME"
										},
										{
											"enum_id": 126,
											"string_id": "MLM_PHM_KEY_MAIN_AMBILIGHT_COMFORT"
										},
										{
											"enum_id": 127,
											"string_id": "MLM_PHM_KEY_MAIN_AMBILIGHT_RELAX"
										}
									]
								}
							},
							{
								"node_id": 130,
								"type": "LIST_NODE",
								"string_id": "MLM_PHM_KEY_MAIN_FOLLOW_AUDIO",
								"icon": null,
								"context": "ambilight_follow_audio",
								"data": {
									"enums": [
										{
											"enum_id": 131,
											"string_id": "MLM_PHM_KEY_MAIN_FOLLOW_AUDIO_STYLE_1"
										},
										{
											"enum_id": 132,
											"string_id": "MLM_PHM_KEY_MAIN_FOLLOW_AUDIO_STYLE_2"
										},
										{
											"enum_id": 133,
											"string_id": "MLM_PHM_KEY_MAIN_FOLLOW_AUDIO_STYLE_3"
										},
										{
											"enum_id": 134,
											"string_id": "MLM_PHM_KEY_MAIN_FOLLOW_AUDIO_STYLE_4"
										},
										{
											"enum_id": 135,
											"string_id": "MLM_PHM_KEY_MAIN_FOLLOW_AUDIO_STYLE_5"
										},
										{
											"enum_id": 136,
											"string_id": "MLM_PHM_KEY_MAIN_FOLLOW_AUDIO_STYLE_6"
										},
										{
											"enum_id": 137,
											"string_id": "MLM_PHM_KEY_MAIN_FOLLOW_AUDIO_STYLE_7"
										}
									]
								}
							},
							{
								"node_id": 140,
								"type": "LIST_NODE",
								"string_id": "MLM_PHM_KEY_MAIN_FOLLOW_COLOUR",
								"icon": null,
								"context": "ambilight_follow_color",
								"data": {
									"enums": [
										{
											"enum_id": 141,
											"string_id": "MLM_PHM_KEY_MAIN_LOUNGE_LIGHT_MODE_2"
										},
										{
											"enum_id": 142,
											"string_id": "MLM_PHM_KEY_MAIN_LOUNGE_LIGHT_MODE_3"
										},
										{
											"enum_id": 143,
											"string_id": "MLM_PHM_KEY_MAIN_LOUNGE_LIGHT_MODE_1"
										},
										{
											"enum_id": 144,
											"string_id": "MLM_PHM_KEY_MAIN_WARM_WHITE"
										},
										{
											"enum_id": 145,
											"string_id": "MLM_PHM_KEY_MAIN_COOL_WHITE"
										}
									]
								}
							},
							{
								"node_id": 150,
								"type": "PARENT_NODE",
								"string_id": "MLM_PHM_KEY_MAIN_FOLLOW_FLAG",
								"icon": null,
								"context": "ambilight_follow_flag",
								"data": {

								}
							},
							{
								"node_id": 160,
								"type": "PARENT_NODE",
								"string_id": "MLM_PHM_KEY_MAIN_FOLLOW_APP",
								"icon": null,
								"context": "ambilight_follow_app",
								"data": {

								}
							}
						]
					}
				},
				{
					"node_id": 200,
					"type": "SLIDER_NODE",
					"string_id": "MLM_PHM_KEY_PC_ID_BRIGH_L12",
					"icon": null,
					"context": "ambilight_brightness",
					"data": {
						"slider_data": {
							"min": 0,
							"max": 10,
							"step_size": 1
						}
					}
				},
				{
					"node_id": 300,
					"type": "SLIDER_NODE",
					"string_id": "MLM_PHM_KEY_ID_AMB_SAT",
					"icon": null,
					"context": "ambilight_saturation",
					"data": {
						"slider_data": {
							"min": -2,
							"max": 2,
							"step_size": 1
						}
					}
				},
				{
					"node_id": 400,
					"type": "PARENT_NODE",
					"string_id": "MLM_PHM_KEY_MAIN_AMBILIGHT_PLUS_HUE",
					"icon": null,
					"context": "ambilight_hue_menu",
					"data": {
						"nodes": [
							{
								"node_id": 410,
								"type": "PARENT_NODE",
								"string_id": "MLM_PHM_KEY_ID_AMB_HUE_CONNECT",
								"icon": null,
								"context": "ambilight_hue_wizard",
								"data": {

								}
							},
							{
								"node_id": 420,
								"type": "TOGGLE_NODE",
								"string_id": "MLM_PHM_KEY_MAIN_AMBILIGHT_HUE_SWITCH_OFF",
								"icon": null,
								"context": "ambilight_hue_off",
								"data": {

								}
							},
							{
								"node_id": 430,
								"type": "PARENT_NODE",
								"string_id": "MLM_PHM_KEY_ID_AMB_HUE_IMM",
								"icon": null,
								"context": "ambilight_hue_follow_ambilight",
								"data": {

								}
							},
							{
								"node_id": 440,
								"type": "PARENT_NODE",
								"string_id": "MLM_PHM_KEY_ID_AMB_HUE_LL",
								"icon": null,
								"context": "ambilight_lounge_light_hue",
								"data": {

								}
							},
							{
								"node_id": 450,
								"type": "PARENT_NODE",
								"string_id": "MLM_PHM_KEY_ID_AMB_HUE_STATUS",
								"icon": null,
								"context": "ambi_hue",
								"data": {

								}
							},
							{
								"node_id": 460,
								"type": "PARENT_NODE",
								"string_id": "MLM_PHM_KEY_MAIN_AMBILIGHT_HUE_RESET",
								"icon": null,
								"context": "ambilight_hue_reset_configuration",
								"data": {

								}
							}
						]
					}
				},
				{
					"node_id": 500,
					"type": "PARENT_NODE",
					"string_id": "MLM_PHM_KEY_ID_AMB_ADV",
					"icon": null,
					"context": "ambilight_advanced",
					"data": {
						"nodes": [
							{
								"node_id": 510,
								"type": "WALL_COLOR_NODE",
								"string_id": "MLM_PHM_KEY_DESC_ID_WALL_L151",
								"icon": null,
								"context": "ambilight_wall_color",
								"data": {
									"colors": [
										-1,
										-1651276,
										-3342439,
										-3347201,
										-3355393,
										-13108,
										-6451,
										-103,
										-12566464,
										-3693173,
										-6565376,
										-10053121,
										-2982751,
										-33664,
										-81560,
										-256,
										-15724528,
										-7508135,
										-10452480,
										-15513423,
										-5293203,
										-1888983,
										-5682169,
										-26368
									],
									"node_id": 520,
									"type": "LIST_NODE",
									"string_id": "MLM_PHM_KEY_ID_SWTH_L148",
									"icon": null,
									"context": "ambilight_tv_switch_off",
									"data": {
										"enums": [
											{
												"enum_id": 1,
												"string_id": "MLM_PHM_KEY_SWITCH_OFF_1"
											},
											{
												"enum_id": 1,
												"string_id": "MLM_PHM_KEY_SWITCH_OFF_2"
											}
										]
									}
								}
							}
						]
					}
				}
			]
		}
	}
}

**Comment by eslavnov** [comment]
Hey @ridwancc,
That's a quite weird menu structure you've got, I've never seen anything like this. Could you please share the output of 'http://tv_ip_address:1926/system'?

**Comment by ridwancc** [comment]
hi @eslavnov,
Thanks for the reply. The TV model number is PUS6703. and the output i get below:

`Sending GET request to http://192.168.1.83:1925/6/system
Request sent!
{
	"menulanguage": "English",
	"name": "43PUS6753/12",
	"country": "United Kingdom",
	"serialnumber_encrypted": "K2kseVsmQFgkd15gKkJ+aiPbvuq2OIZYqMR2oK1DHjw=",
	"softwareversion_encrypted": "K2kseVsmQFgkd15gKkJ+ak3ednbEwu0L3RKYbs0Gj1xlrFBUFQZWhdSTO1BqwGdd",
	"model_encrypted": "K2kseVsmQFgkd15gKkJ+atzi/ChqBb8Y0yxN8VXWLIw=",
	"deviceid_encrypted": "K2kseVsmQFgkd15gKkJ+ahTsr+UfU1foSvF1xmj3cMg=",
	"nettvversion": "4.6.0.1",
	"epgsource": "no_epg",
	"api_version": {
		"Major": 6,
		"Minor": 1,
		"Patch": 0
	},
	"featuring": {
		"jsonfeatures": {
			"recordings": [
				"List",
				"Schedule",
				"Manage"
			],
			"ambilight": [
				"Hue",
				"Ambilight"
			],
			"textentry": [
				"context_based",
				"initial_string_available"
			],
			"inputkey": [
				"key",
				"unicode"
			],
			"pointer": [
				"context_based"
			],
			"activities": [
				"browser"
			]
		},
		"systemfeatures": {
			"tvtype": "consumer",
			"content": [
				"dmr"
			],
			"pairing_type": "none",
			"os_type": "Linux"
		}
	}
}

`

**Comment by Brunty** [comment]
I have a menu structure very similar at first glance to the structure above - my model number is `50PUS6704/12`.

I ran `python3 pylips.py --command get --path 'menuitems/settings/structure' --verbose True > settings_dump.txt` to get the structure when ambilight was off, and then ran it again (but changed the output to `settings_dump_on.txt`) and diffed the files, they're the same as each other.

**Comment by ridwancc** [comment]
if I use the command "ambilight_off" it switches the ambilight+hue off. "ambilight_on" sets my the tv ambilight to app. Those are the only two that work. I just want to toggle ambilight+hue but it seems the commands are mixed up for my tv.

**Comment by eslavnov** [comment]
Ok guys, I've finally sorted out all of my personal stuff, so now I have some time to work on this issue. 

Talking about "Ambilight + hue", it seems that it works differently depending on a TV's model. So far I have seen:
1) "Regular" TV where ambilight+hue is controlled by nodeid 2131230774 (I call them "regular" purely because this is how it behaves on my TV and all the TVs I've seen before this issue).
2) TVs like 55PUS7304, where it works the same but uses a different nodeid (2131230778). I wonder if there are other models where the nodeid is also different.
3) TVs like 43PUS6753 mentioned by @ridwancc, which have a completely different menu structure. The issue here is that this structure does not have a data payload that can be used to toggle ambilight + hue, so unfortunately the approach used for other models won't fly here.

I've also noticed that the TVs in cases 1) and 2) are Android models, while in case 3) it's a Linux TV. So it seems like we can toggle Ambilight+hue on Android models only. It might be possible to toggle this for Linux models, but since I don't have such a model, there is not much I can do.

For Android models, I'll write some logic to auto-detect the right nodeid, so the next Pylips version should work for all models. It's an easy addition, but there are a bunch of older issues I need to take care of first, so expect a new version in a week or two.

For Linux models, somebody needs to try the official Philips remote app: if you can toggle the Ambilight+ Hue with it then we just need to capture the traffic with something like Wireshark/Charles, and I'll likely be able to add this to Pylips.

**Comment by ridwancc** [comment]
I've tried using the phone app but it just doesn't connect to my TV, hasn't worked for a few months. 
I'm not sure if this will help but when I send the this command: 
`python3 pylips.py --command post --path 'menuitems/settings/current' --body '{"nodes":[{"nodeid":420}]}'`
I get the response: 
`{
        "values": [
                {
                        "value": {
                                "Nodeid": 420,
                                "Controllable": true,
                                "Available": true,
                                "string_id": "Switch off",
                                "data": {
                                        "value": true
                                }
                        }
                }
        ]
}`
value changes to false when ambilight+hue is on and true when it is off.

**Comment by Brunty** [comment]
@ridwancc I get the same results on my TV!

**Comment by FeikoJoosten** [comment]
Sorry for joining into the conversation. But I'm guessing that if your tv does not support the ambilight feature, there's no way of turning it on through the API? This way, I could for example use the information from the ambilight to send it an external RGB strip to make use of my own implementation of ambilight. 

if I run the ambilight status command I onlý get the following:
```
python3 pylips.py --host 192.168.0.107 --command ambihue_status
Sending POST request to http://192.168.0.107:1925/6/menuitems/settings/current
Request sent!

{
        "values": [
                {
                        "value": {

                        }
                }
        ]
}
```

**Comment by eslavnov** [comment]
> I've tried using the phone app but it just doesn't connect to my TV, hasn't worked for a few months.
> I'm not sure if this will help but when I send the this command:
> `python3 pylips.py --command post --path 'menuitems/settings/current' --body '{"nodes":[{"nodeid":420}]}'`
> I get the response:
> `{ "values": [ { "value": { "Nodeid": 420, "Controllable": true, "Available": true, "string_id": "Switch off", "data": { "value": true } } } ] }`
> value changes to false when ambilight+hue is off and true when it is on.

Try running this:  `python3 pylips.py --command post --path menuitems/settings/update --body '{ "values": [{ "value": { "Nodeid": 420, "Controllable":true, "Available": true, "data": { "value": true } } }] }'`. Replace `"value": true` with `"value": false` for an opposite effect. Let me know if it works!

**Comment by eslavnov** [comment]
@FeikoJoosten `ambihue_status` is not an Ambilight status command, but the status for Ambilight+Hue. Check the wiki for Ambilight-related commands to see what's possible. Probably [this one](https://github.com/eslavnov/pylips/wiki/Ambilight-cached-(GET)) would be useful.

**Comment by FeikoJoosten** [comment]
@eslavnov Thanks for coming back to me. Interestingly enough, the [supported styles](https://github.com/eslavnov/Pylips/wiki/Ambilight-supported-styles-(GET)) command does give me multiple supported styles. But the cached, measured, processed commands are all empty for my. (Yes the Ambilight Power does return `On`). 

I’m guessing that since my tv model doesn’t actually have ambilight. The processor does nothing with it. But since there’s support for it in the software I can enable the ambilight.

**Comment by ridwancc** [comment]
I downloaded the older version of the Philips tv remote app and that connects fine to my TV. The Ambilight+hue button doesn't toggle the settings on TV it only shows whether it is on or off. So I guess that confirms its not possible to toggle ambilight+hue in this way if the official app doesn't support it. The only way I can imagine this would work is by somehow interrupting the connection of the TV with the hue Bridge when you want to switch off ambilight+hue.

**Comment by 10w73** [comment]
> Ok guys, I've finally sorted out all of my personal stuff, so now I have some time to work on this issue.
> 
> Talking about "Ambilight + hue", it seems that it works differently depending on a TV's model. So far I have seen:
> 
> 1. "Regular" TV where ambilight+hue is controlled by nodeid [2131230774](tel:2131230774) (I call them "regular" purely because this is how it behaves on my TV and all the TVs I've seen before this issue).
> 2. TVs like 55PUS7304, where it works the same but uses a different nodeid ([2131230778](tel:2131230778)). I wonder if there are other models where the nodeid is also different.
> 3. TVs like 43PUS6753 mentioned by @ridwancc, which have a completely different menu structure. The issue here is that this structure does not have a data payload that can be used to toggle ambilight + hue, so unfortunately the approach used for other models won't fly here.
> 
> I've also noticed that the TVs in cases 1) and 2) are Android models, while in case 3) it's a Linux TV. So it seems like we can toggle Ambilight+hue on Android models only. It might be possible to toggle this for Linux models, but since I don't have such a model, there is not much I can do.
> 
> For Android models, I'll write some logic to auto-detect the right nodeid, so the next Pylips version should work for all models. It's an easy addition, but there are a bunch of older issues I need to take care of first, so expect a new version in a week or two.
> 
> For Linux models, somebody needs to try the official Philips remote app: if you can toggle the Ambilight+ Hue with it then we just need to capture the traffic with something like Wireshark/Charles, and I'll likely be able to add this to Pylips.

Any updates on this? Is there maybe a beta? For me nodeid 2131230778 works. I would love to read the correct Ambihue state for an mqtt switch I want to implement in homebridge. 

Or is there something I can more or less easily change somewhere to have the correct state in the mqtt status? Right now it says Ambihue is „5“.

**Comment by Mr-Groch** [comment]
Hi, I also have non Android Philips TV from 2019 year (55PUS6754/12). And I have similar menu structure like @ridwancc  above. Node with switch:

```
							{
								"node_id": 420,
								"type": "TOGGLE_NODE",
								"string_id": "MLM_PHM_KEY_MAIN_AMBILIGHT_HUE_SWITCH_OFF",
								"icon": null,
								"context": "ambilight_hue_off",
								"data": {

								}
							},
```

`{"nodes":[{"nodeid":420}]}` on `http://192.168.1.125:1925/6/menuitems/settings/current`  gives me current ambilight+hue status properly:

```
{
        "version": 1,
        "values": [
                {
                        "value": {
                                "Nodeid": 420,
                                "Controllable": true,
                                "Available": true,
                                "string_id": "Switch off",
                                "data": {
                                        "value": false
                                }
                        }
                }
        ]
}
```

But can't set it with `{ "values": [{ "value": { "Nodeid": 420, "Controllable":true, "Available": true, "data": { "value": true } } }] }` on `http://192.168.1.125:1925/6/menuitems/settings/update`


But I have tried official Philips TV remote app (new version) and I can control ambilight+hue from there! I can even move my light bulbs around TV in virtual room map in app. There also is app in google play named New Ambilight+Hue - this app asor works - I can switch ambilight+hue on/off.

How can I help to catch those requests from app? I don't have much experience with that....

**Comment by Mr-Groch** [comment]
OK, I have found it myself. I've used httpCanary app to sniff traffic from my smarphone. Controlling Ambilight+Hue is pretty simple:

### To check status of Ambilight+Hue you have 2 options:
1. POST `{"nodes":[{"nodeid":420}]}` to `http://tv_ip:1925/6/menuitems/settings/current`. But `nodeid` may be different on each TV model - you have to GET `http://tv_ip:1925/6/menuitems/settings/structure` and find node with `"context": "ambilight_hue_off"`
2. GET on `http://tv_ip:1925/6/HueLamp/power`, you will get response:
```
{
	"power": "Off"
}
```
Power can by `On `or `Off`

### To set Ambilight+Hue on or off:
POST `{"power":"Off"}` to turn off or `{"power":"On"}` to turn on to `http://tv_ip:1925/6/HueLamp/power`

That's all! :smiley:

**Comment by eslavnov** [comment]
Thanks for the feedback, everybody! Starting from version 1.3.0 Pylips now should handle Ambilight+Hue correctly on all models.
