### ISSUE TITLE
Standard Lounge Light Scenes

### ISSUE THREAD

**Issue by Nastras** [eslavnov/pylips#61]
Hello and many thanks for the tool.

I have discovered that it is also possible to call up the standard Lounge Light scenes via :
192.168.XXX.XX:1925/6/ambilight/currentconfiguration

Maybe you would like to record them as well?

Here are the bodies for it:

{
    "styleName": "FOLLOW_COLOR",
    "isExpert": false,
    "menuSetting": "HOT_LAVA",
    "stringValue": "Hot Lava"
}

------------------------------------------

{
    "styleName": "FOLLOW_COLOR",
    "isExpert": false,
    "menuSetting": "ISF",
    "stringValue": "Warm White"
}

------------------------------------------

{
    "styleName": "FOLLOW_COLOR",
    "isExpert": false,
    "menuSetting": "PTA_LOUNGE",
    "stringValue": "Cool White"
}

------------------------------------------

{
    "styleName": "FOLLOW_COLOR",
    "isExpert": false,
    "menuSetting": "FRESH_NATURE",
    "stringValue": "Fresh Nature"
}

------------------------------------------

{
    "styleName": "FOLLOW_COLOR",
    "isExpert": false,
    "menuSetting": "DEEP_WATER",
    "stringValue": "Deep Water"
}

Best Regards
Nastras

**Comment by eslavnov** [comment]
Hi! 

Thanks for your input! Could you please share the results of calling 'http://ip-address:1925/6/ambilight/supportedstyles'? Your menuSettings are different from mine and I wonder if the endpoint above would give you the same options or not.

Thanks in advance!

**Comment by Nastras** [comment]
The standard scenes are not shown here, to get them you have to switch on the scenes with the lounge light button on the remote control and then read them out with:  

http://ip-adress:1925/6/ambilight/currentconfiguration

Afterwards you can use this via the API with:
POST 192.168.XXX.XX:1925/6/ambilight/currentconfiguration (BODY)

Let me know if it works.-)

{
    "supportedStyles": [
        {
            "styleName": "OFF"
        },
        {
            "styleName": "FOLLOW_VIDEO"
        },
        {
            "styleName": "FOLLOW_AUDIO",
            "algorithms": [
                "ENERGY_ADAPTIVE_BRIGHTNESS",
                "ENERGY_ADAPTIVE_COLORS",
                "VU_METER",
                "SPECTRUM_ANALYZER",
                "KNIGHT_RIDER_CLOCKWISE",
                "KNIGHT_RIDER_ALTERNATING",
                "RANDOM_PIXEL_FLASH",
                "STROBO",
                "PARTY"
            ],
            "maxTuning": 2
        },
        {
            "styleName": "FOLLOW_COLOR",
            "algorithms": [
                "MANUAL_HUE",
                "AUTOMATIC_HUE"
            ],
            "maxSpeed": 255
        },
        {
            "styleName": "LOUNGE"
        },
        {
            "styleName": "MANUAL"
        },
        {
            "styleName": "EXPERT"
        },
        {
            "styleName": "GRID"
        },
        {
            "styleName": "FLAG"
        },
        {
            "styleName": "APP"
        }
    ]
}

**Comment by Nastras** [comment]
I wanted to see if it worked?

**Comment by eslavnov** [comment]
Thanks, @Nastras! It worked, I've added it to the latest version of Pylips!

**Comment by Nastras** [comment]
Hey cool that it works and you implemented it. Thanks a lot!
