### ISSUE TITLE
Unknown API on 50PUS7394

### ISSUE THREAD

**Issue by meltedhaggis** [eslavnov/pylips#62]
"IP 192.168.0.223 is online, but no known API is found. Exiting..."

If its something you're interested in sorting and I can help let me know

**Comment by eslavnov** [comment]
Hey, this model behaves a bit strange, check out this [issue](https://github.com/eslavnov/pylips/issues/51). Does the mobile Philips TV remote app work for you? If yes, and you are willing to spend some time capturing the traffic (I'll give you instructions to follow), I might be able to sort it out. Otherwise there is not much I can do, since I don't own this particular model.

**Comment by iffa** [comment]
Issue also presents itself on 55PUS7334. Official remote app doesn't work, ports 1925 and 1926 are seemingly closed.

**Comment by svatos-jirka** [comment]
The same issue for Phillips model 55PUS7304. Please help. What can I analyzed?

**Comment by svatos-jirka** [comment]
> The same issue for Phillips model 55PUS7304. Please help. What can I analyzed? Or is there another way (node red)?

HI,

for any reason, it works now. I dont know why. I didnt change anything (I tried to enable debug on TV, but then I disabled it again). Phillips remote app  didnt want to work too. But after cca 1 hour, the app was able to connect.

**Comment by eslavnov** [comment]
Yeah, this happens sometimes (the API stops responding). I thought that it was an issue with Pylips, but a) I've fixed it in one of the previous versions and b) the official app also does not work. This tells me that it is an API problem, not a Pylips issue. Unfortunately, there is nothing I can do about it!

**Comment by emivaljr** [comment]
I had the same issue on my Saphi OS TV and the solution is to enable WoWLAN option:
Network -> Switch on with Wi-FI(WoWLAN). It comes by default off. 
After that, I was able to call the API on 1925 port.
