### ISSUE TITLE
MQTT volume command

### ISSUE THREAD

**Issue by ytrufchev** [eslavnov/pylips#64]
I can't get the volume command to work over mqtt by using {{"command":"volume","body":{"value":10}}
Am I doing something wrong.

**Comment by eslavnov** [comment]
Hi @ytrufchev,

The `volume` command does not support setting the volume to a specific level: it just returns the current volume (but you won't see any response if you use it with MQTT). 

To change the volume with MQTT, you could use the following command: `{"command": "volume_up"}`. It will increase (or decrease if using `volume_down`) the volume by 1 step from the current level.

**Comment by ytrufchev** [comment]
Thank you
