### ISSUE TITLE
[FEAT] Launch shutdown/restart menu

### ISSUE THREAD

**Issue by popy2k14** [eslavnov/pylips#65]
Hey @eslavnov,

hope you and your family are doing well these days?

I have an idea regarding launching the shutdown/restart menu on the android TV over pylips.

In the toengel blog there is an interesting entry which allows to map the shutdown/restart menu to any button (except standby). Also starting apps, activities can be launched this way!

Here it is: https://toengel.net/philipsblog/2020/04/02/philips-android-tv-fernbedienung-neu-belegen-neustart-restart-dialog-anzeigen/

Launching apps is already supported by pylips and using activities (as i understand, sorry not so deep in android).

So would it be possible to send the "show shutdown/restart" activity over pylips to the tv?

thanks a lot
Tobias

**Comment by eslavnov** [comment]
Hey @popy2k14 ,

Good to hear from you! We are doing well, how are you?

Unfortunately, I am not familiar with the intent/activity required to show this menu. I am also not getting anything from the API when I use `activities/current` command when this menu is open, so I am not sure it's possible. I'll re-open this issue if I stumble upon a solution, but I would not count on that. 

I'd say the easiest solution is indeed to use the Button Mapper app (I've been using it myself for several years) with a combination of Pylips's send key command - just remap one of the keys to show this menu and use Pylips to trigger that key.

**Comment by popy2k14** [comment]
Hi @eslavnov .

Thanks, we are fine too.

Thanks for the hint!
Finally i have an easy accessible shutdown/reboot menu.
