### ISSUE TITLE
[FEAT] Silent Reboot

### ISSUE THREAD

**Issue by popy2k14** [eslavnov/pylips#72]
Using pylips in mqtt mode now on an 65pus8102 and 55pus9104, it works really good!!
Since activating alexa on the TV sets it doesn't deactivate the network interfaces in standby (I think it just don't go in any sleep mode) and I am able to wake it with pylips sending standby key.

Sadly in my case, after a few days the sound over my avr (connected with ARC) is choppy. A manual restart of the TV set, solves the issue.

So my feature request! / question is a silent, scheduled reboot with pylips.

PS. : adb reboot is working but not silent

Is this possible?

Thx

**Comment by eslavnov** [comment]
Hey @popy2k14 ,

What exactly do you mean with a 'silent reboot'? `adb reboot` works nicely for me, so I am not sure what is the behavior you would like to see?

**Comment by popy2k14** [comment]
Yeah, also using adb reboot now at night in the living room and day in bed room to reboot my devices on an daily basis.

With silent I mean, that the display of the TV is OFF during reboot.

**Comment by eslavnov** [comment]
Hey @popy2k14,

I've done some research but so far I had no luck with the 'silent' reboot :( I'll keep an eye on this feature request, though - I might think of something in the future.

**Comment by popy2k14** [comment]
Thanks a lot.
