### ISSUE TITLE
pylips and home assistant install?

### ISSUE THREAD

**Issue by ShifuEst** [eslavnov/pylips#79]
Hello

Could you please do a tutorial on how to install it. (Home assistant raspberry pi) My tv is philips sahpi OS.

to which folder should I move these files? and which files?

thank you 

**Comment by eslavnov** [comment]
Hi, 

There are no specific installation instructions. Copy the repo to any folder, navigate inside it and run the commands from the Readme ("Prerequisites" and "Setting up Pylips"). 

For home assistant you are probably better off using this component (not related to Pylips): https://github.com/nstrelow/ha_philips_android_tv

**Comment by ShifuEst** [comment]
But i’m not use android. I use saphi

Lugupidamisega, Marek

📞 +372 57 80 80 70
✉️ marek.uuk@gmail.com
________________________________
Saatja: Evgeny Slavnov <notifications@github.com>
Saadetud: Monday, October 19, 2020 3:59:07 PM
Adressaat: eslavnov/pylips <pylips@noreply.github.com>
Koopia: ShifuEst <marek.uuk@gmail.com>; Author <author@noreply.github.com>
Teema: Re: [eslavnov/pylips] pylips and home assistant install? (#79)


Closed #79<https://github.com/eslavnov/pylips/issues/79>.

**Comment by eslavnov** [comment]
@ShifuEst most of the commands will work on Saphi, but not all (you can search the issues to understand what works and what does not). Same is probably true for the component I've mentioned above since it's using the same API.
