### ISSUE TITLE
Help me

### ISSUE THREAD

**Issue by ZoltXs** [eslavnov/pylips#88]
Hi, I need someone to help me with the settings. I have run this command to the terminal and correct, and I would like to know if the settings for the settings.ini file is filled with the correct data

[DEFAULT]
verbose = True
MQTT_listen = False
MQTT_update = False
num_retries = 3
update_interval = 3
[TV]
host = 192.168.0.27
port = 1926
apiv =  6
user = pczyoRn3qriN9jsq
pass = f20d23004e7e72a2f5980eb47c091bb2adca56da5ead6d53197b3107d0df03a9
protocol = 
[MQTT]
host = 
port = 
user = 
pass = 
TLS = False
cert_path =
topic_pylips = 
topic_status = 

——-——————-———-——

jbnoxs@MiniNoXs ~ % python3 /Users/jbnoxs/Documents/philips_android_tv-master/philips.py   
usage: philips.py [-h] [--host HOST] [--user USER] [--pass PASSWORD] command
philips.py: error: the following arguments are required: command

**Comment by ZoltXs** [comment]
What do I do wrong?

**Comment by eslavnov** [comment]
You are trying to run "philips_android_tv-master/philips.py", which is a separate project that is not related to Pylips in any way. Check your paths and make sure you are actually calling Pylips.
