### ISSUE TITLE
[API DOCS] Ambilight: `/cached`, `/lounge` & `isExpert`

### ISSUE THREAD

**Issue by buschtoens** [eslavnov/pylips#89]
Semi-related to #70.

Thanks a lot for this excellent project and the reverse-engineered docs. I wouldn't have looked deeper into all of this, if it wasn't for your fundamental work!

I noticed that the docs around `/cached` & `/lounge`, as well as the `isExpert` option on `/currentconfiguration` are very thin. I got nerd-sniped and dicked around with the [Philips TV Remote app](https://www.philips.com/c-w/country-selectorpage/tv/tv-remote-app.html). No fancy MITM (yet); just triggering something in the app and then querying the different `GET` endpoints to see what changed.

I have a pretty clear picture of how to use these configs now and would like to contribute them back. As the wiki is only writable for collaborators, what would be your preferred way for me to upstream the changes?

- I summarize them here.
- I fork the wiki `.git` and push it to a repo.
- You make me a collaborator.
- You lift the wiki write access restriction.
- The wiki gets obsoleted and the content is moved to this repo or a separate repo. Docs could be auto-deployed to GitHub Pages, e.g. using Jekyll.

**Comment by eslavnov** [comment]
Hi @buschtoens! 

Thank you for your input! I've been thinking about moving the docs to the repo and this is a nice extra motivation for me to do this! I'll handle it over the weekend and then you can create a PR with your updates (which would be extremely welcomed!).

**Comment by buschtoens** [comment]
Fantastic! Let me know, once you're ready and I'll get to it. 😊

**Comment by eslavnov** [comment]
Hi @buschtoens, my apologies for the delay,  but I've finally moved the docs into the repo so feel free to send a PR with your contributions! Thanks in advance!
