### ISSUE TITLE
[Question] Blinking Ambilgiht

### ISSUE THREAD

**Issue by gprsnlty** [eslavnov/pylips#97]
This is probably not script related im just curios if anyone else has this problem or ideas why this happens.

Whenever I set the Ambilight color via the api it stays on for about 30sec, turns off and turns back on. 
This repeats until I turn the Ambilight off.
I don't have any issues when using Ambilight via the Remote its just when I use the Api.

These commands for me all rusult in the same blinking behavior.
`curl -X POST http://<TV-IP>:1925/6/`...

..`ambilight/cached -d "{"r": 100, "g": 210, "b": 30}"`

...`mbilight/lounge -d "{"color":{"hue":155,"saturation":240,"brightness":180},"colordelta": {"hue":20,"saturation":25,"brightness":100},"speed":255,"mode":"Default"}"`

...`ambilight/currentconfiguration -d "{"styleName": "FOLLOW_COLOR", "isExpert": "false", "menuSetting": "FRESH_NATURE", "stringValue": "Fresh Nature"}"`

**Comment by eslavnov** [comment]
Hi @gprsnlty!

Wow, I've never seen anything like this before. How does Ambilight behave when using the official Philips mobile remote app?

Also, try turning MQTT listen off (if it's on) - it's highly unlikely that it's the issue, but good to check anyways.

Finally, are you absolutely sure you are not running any other tools that talk to the TV (or multiple instances of Pylips) in parallel?

**Comment by gprsnlty** [comment]
Hi thank you for your response!

It behaves the same when i use the app. So this seams to be an issue with the TV itself right? 

I manually did the curl so your script defiantly does not interfere with MQTT listen or a secondary running instance.
I asked here just because I hoped the issue is known.

Do you have any clue like is this a Software issue? could external hdmi devices have any affect on this. Otherwise I close this now since it is not script realted.
If I find anything I comment here and thank you again!
